# Generated by Django 4.1.7 on 2023-05-09 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_compra_cartao_avaliacao'),
    ]

    operations = [
    ]
