# Generated by Django 4.1.7 on 2023-05-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_time_remove_produto_time_coracao_produto_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='time',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_coracao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
