# Generated by Django 4.1.7 on 2023-05-25 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_produto_equipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='equipe',
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=200)),
                ('produto', models.CharField(max_length=200)),
                ('comentario', models.TextField()),
                ('data_devolucao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
