# Generated by Django 4.2.1 on 2023-06-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_produto_equipe_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),

        migrations.AddField(
            model_name='carrinho',
            name='produto',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
