# Generated by Django 4.2.1 on 2023-06-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_carrinho_preco_carrinho_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='produto',
            field=models.CharField(default='', max_length=100),
        ),
    ]
