# Generated by Django 4.2.1 on 2023-06-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_remove_carrinho_preco_remove_carrinho_produto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='produtos',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='total_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='total_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
